export const noticeDetails = [
  {
    id: 32539424,
    title: 'Nobody Wants to Teach Anymore',
    points: 80,
    createdAt: 'grej',
    time: 1661084318,
    time_ago: 'an hour ago',
    comments_count: 84,
    type: 'link',
    url: 'https://jessicalexicus.medium.com/nobody-wants-to-teach-anymore-66f09b877b11',
    domain: 'jessicalexicus.medium.com',
  },
  {
    id: 32497780,
    title: 'There’s no speed limit (2009)',
    points: 471,
    createdAt: 'melling',
    time: 1660750774,
    time_ago: '4 days ago',
    comments_count: 220,
    type: 'link',
    url: 'https://sive.rs/kimo',
    domain: 'sive.rs',
  },
  {
    id: 32539455,
    title: "LibGen's Bloat Problem",
    points: 8,
    createdAt: 'liberalgeneral',
    time: 1661084576,
    time_ago: 'an hour ago',
    comments_count: 1,
    type: 'link',
    url: 'https://liberalgeneral.neocities.org/libgens-bloat-problem/',
    domain: 'liberalgeneral.neocities.org',
  },
  {
    id: 32494839,
    title:
      'Physically Based: A Database of PBR Values for Real-World Materials',
    points: 32,
    createdAt: 'ibobev',
    time: 1660736005,
    time_ago: '4 days ago',
    comments_count: 6,
    type: 'link',
    url: 'https://80.lv/articles/physically-based-a-database-of-pbr-values-for-real-world-materials/',
    domain: '80.lv',
  },
  {
    id: 32538223,
    title: 'The Excellent Schemer',
    points: 48,
    createdAt: 'signa11',
    time: 1661068653,
    time_ago: '5 hours ago',
    comments_count: 4,
    type: 'link',
    url: 'https://code-magazine.com/Article/2207071/The-Excellent-Schemer',
    domain: 'code-magazine.com',
  },
  {
    id: 32539360,
    title: 'Turning SQLite into a Distributed Database',
    points: 9,
    createdAt: 'losfair',
    time: 1661083763,
    time_ago: 'an hour ago',
    comments_count: 0,
    type: 'link',
    url: 'https://univalence.me/posts/mvsqlite',
    domain: 'univalence.me',
  },
  {
    id: 32495146,
    title: 'Book Review: Unlearn Your Pain (2016)',
    points: 12,
    createdAt: 'bfoks',
    time: 1660737907,
    time_ago: '4 days ago',
    comments_count: 1,
    type: 'link',
    url: 'https://slatestarcodex.com/2016/06/26/book-review-unlearn-your-pain/',
    domain: 'slatestarcodex.com',
  },
  {
    id: 32539762,
    title: 'Apple builds new ad empire after kneecapping competitors',
    points: 7,
    createdAt: 'galogon',
    time: 1661087146,
    time_ago: '14 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://www.axios.com/2022/08/21/apple-advertising-privacy-tracking-iphone',
    domain: 'axios.com',
  },
  {
    id: 32539444,
    title: 'New chip ramps up AI computing efficiency',
    points: 4,
    createdAt: 'rbanffy',
    time: 1661084451,
    time_ago: 'an hour ago',
    comments_count: 0,
    type: 'link',
    url: 'https://news.stanford.edu/2022/08/18/new-chip-ramps-ai-computing-efficiency/',
    domain: 'news.stanford.edu',
  },
  {
    id: 32539123,
    title:
      '-------------Silent crisis of soaring excess deaths in Britain is only tip of the iceberg',
    points: 81,
    createdAt: 'danboarder',
    time: 1661081085,
    time_ago: '2 hours ago',
    comments_count: 90,
    type: 'link',
    url: 'https://uk.news.yahoo.com/silent-crisis-soaring-excess-deaths-203000290.html',
    domain: 'uk.news.yahoo.com',
  },
  {
    id: 32520198,
    title: 'Software-defined satellite enters commercial service',
    points: 73,
    createdAt: 'olvy0',
    time: 1660912449,
    time_ago: '2 days ago',
    comments_count: 13,
    type: 'link',
    url: 'https://www.spacedaily.com/m/reports/Software_defined_satellite_enters_commercial_service_999.html',
    domain: 'spacedaily.com',
  },
  {
    id: 32538545,
    title: 'Wreck of SMS Kaiser Franz Joseph',
    points: 11,
    createdAt: 'Domobran7',
    time: 1661073257,
    time_ago: '4 hours ago',
    comments_count: 2,
    type: 'link',
    url: 'https://historyandwar.org/2022/08/21/wreck-of-sms-kaiser-franz-joseph/',
    domain: 'historyandwar.org',
  },
  {
    id: 32536808,
    title: 'Hacking around with the ScotRail audio announcements',
    points: 79,
    createdAt: 'simonw',
    time: 1661047855,
    time_ago: '11 hours ago',
    comments_count: 19,
    type: 'link',
    url: 'https://simonwillison.net/2022/Aug/21/scotrail/',
    domain: 'simonwillison.net',
  },
  {
    id: 32534389,
    title: "A demo of GPT-3's ability to understand long instructions",
    points: 131,
    createdAt: 'monort',
    time: 1661022188,
    time_ago: '18 hours ago',
    comments_count: 51,
    type: 'link',
    url: 'https://twitter.com/goodside/status/1557524546412052482',
    domain: 'twitter.com',
  },
  {
    id: 32537565,
    title: 'Why don’t we do email verification in reverse?',
    points: 194,
    createdAt: 'splash123',
    time: 1661058536,
    time_ago: '8 hours ago',
    comments_count: 222,
    type: 'link',
    url: 'https://blog.yossarian.net/2022/08/20/Why-dont-we-do-email-verification-in-reverse',
    domain: 'blog.yossarian.net',
  },
  {
    id: 32538805,
    title:
      'A dad took photos of his naked child for a doctor; Google reported him to police',
    points: 341,
    createdAt: 'dklsf',
    time: 1661076942,
    time_ago: '3 hours ago',
    comments_count: 194,
    type: 'link',
    url: 'https://www.nytimes.com/2022/08/21/technology/google-surveillance-toddler-photo.html',
    domain: 'nytimes.com',
  },
  {
    id: 32535942,
    title: 'How can we develop transformative tools for thought? (2019) [pdf]',
    points: 108,
    createdAt: 'stopachka',
    time: 1661036787,
    time_ago: '14 hours ago',
    comments_count: 32,
    type: 'link',
    url: 'https://numinous.productions/ttft/print/TTFT.pdf',
    domain: 'numinous.productions',
  },
  {
    id: 32539011,
    title:
      'Flight Simulator 2022: Ultra Realism on RTX 3090 with $100 Graphics Mods [video]',
    points: 24,
    createdAt: 'doener',
    time: 1661079892,
    time_ago: '2 hours ago',
    comments_count: 13,
    type: 'link',
    url: 'https://www.youtube.com/watch?v=lBIqHC6kbX0',
    domain: 'youtube.com',
  },
  {
    id: 32534173,
    title: 'Brian Kernighan adds Unicode support to Awk',
    points: 517,
    createdAt: 'ducktective',
    time: 1661020351,
    time_ago: '19 hours ago',
    comments_count: 143,
    type: 'link',
    url: 'https://github.com/onetrueawk/awk/commit/9ebe940cf3c652b0e373634d2aa4a00b8395b636',
    domain: 'github.com',
  },
  {
    id: 32518360,
    title: '-------------On Being Busy',
    points: 106,
    createdAt: 'aadillpickle',
    time: 1660894023,
    time_ago: '2 days ago',
    comments_count: 66,
    type: 'link',
    url: 'https://blog.aadilali.com/posts/busy.html',
    domain: 'blog.aadilali.com',
  },
  {
    id: 32520365,
    title: 'C++ Concurrency Model on x86 for Dummies (2020)',
    points: 100,
    createdAt: 'greghn',
    time: 1660913666,
    time_ago: '2 days ago',
    comments_count: 49,
    type: 'link',
    url: 'http://databasearchitects.blogspot.com/2020/10/c-concurrency-model-on-x86-for-dummies.html',
    domain: 'databasearchitects.blogspot.com',
  },
  {
    id: 32536590,
    title: 'Beyond Hyperanthropomorphism',
    points: 53,
    createdAt: 'otoburb',
    time: 1661044984,
    time_ago: '12 hours ago',
    comments_count: 76,
    type: 'link',
    url: 'https://studio.ribbonfarm.com/p/beyond-hyperanthropomorphism',
    domain: 'studio.ribbonfarm.com',
  },
  {
    id: 32534684,
    title: 'The Creedence Clearwater Revival Revival',
    points: 91,
    createdAt: 'tintinnabula',
    time: 1661024935,
    time_ago: '18 hours ago',
    comments_count: 69,
    type: 'link',
    url: 'https://www.newyorker.com/culture/cultural-comment/the-creedence-clearwater-revival-revival',
    domain: 'newyorker.com',
  },
  {
    id: 32538322,
    title: 'There were almost two internets. Then, the CIA destroyed one',
    points: 70,
    createdAt: 'thereare5lights',
    time: 1661070130,
    time_ago: '5 hours ago',
    comments_count: 27,
    type: 'link',
    url: 'https://mashable.com/article/project-cybersyn-chile-kernel-panic',
    domain: 'mashable.com',
  },
  {
    id: 32534907,
    title: 'Show HN: Brew.fm – Let bots discover new music on Spotify for you',
    points: 101,
    createdAt: 'bartproost',
    time: 1661026994,
    time_ago: '17 hours ago',
    comments_count: 48,
    type: 'link',
    url: 'https://www.brew.fm/',
    domain: 'brew.fm',
  },
  {
    id: 32519532,
    title: 'Complex of 500 standing stones found in Spain',
    points: 54,
    createdAt: 'pseudolus',
    time: 1660906861,
    time_ago: '2 days ago',
    comments_count: 24,
    type: 'link',
    url: 'https://phys.org/news/2022-08-huge-complex-stones-spain.html',
    domain: 'phys.org',
  },
  {
    id: 32534109,
    title: "A competitive multiplayer version of Conway's Game of Life",
    points: 132,
    createdAt: 'Use',
    time: 1661019808,
    time_ago: '19 hours ago',
    comments_count: 34,
    type: 'link',
    url: 'http://lifecompetes.com',
    domain: 'lifecompetes.com',
  },
  {
    id: 32539828,
    title: 'iOS VPNs have leaked traffic for years, researcher claims',
    points: 3,
    createdAt: 'doener',
    time: 1661087646,
    time_ago: '6 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://arstechnica.com/information-technology/2022/08/ios-vpns-still-leak-traffic-more-than-2-years-later-researcher-claims/',
    domain: 'arstechnica.com',
  },
  {
    id: 32518722,
    title: 'Flang: LLVM’s Fortran Front End',
    points: 79,
    createdAt: 'amirmasoudabdol',
    time: 1660898327,
    time_ago: '2 days ago',
    comments_count: 7,
    type: 'link',
    url: 'https://flang.llvm.org/docs/',
    domain: 'flang.llvm.org',
  },
  {
    id: 32536494,
    title: '-------------Ivy (YC W23) is hiring developers to help unify ML',
    points: null,
    createdAt: null,
    time: 1661043691,
    time_ago: '12 hours ago',
    comments_count: 0,
    type: 'job',
    url: 'https://www.ycombinator.com/companies/ivy/jobs',
    domain: 'ycombinator.com',
  },
  {
    id: 32539828,
    title: '2222222222iOS VP years, researcher claims',
    points: 3,
    createdAt: 'doener',
    time: 1661087646,
    time_ago: '6 minutes ago',
    comments_count: 0,
    type: 'link',
    url: 'https://arstechnica.com/information-technology/2022/08/ios-vpns-still-leak-traffic-more-than-2-years-later-researcher-claims/',
    domain: 'arstechnica.com',
  },
  {
    id: 32518722,
    title: '12312312312312Flang: LLVM’s Fortran Front End',
    points: 79,
    createdAt: 'amirmasoudabdol',
    time: 1660898327,
    time_ago: '2 days ago',
    comments_count: 7,
    type: 'link',
    url: 'https://flang.llvm.org/docs/',
    domain: 'flang.llvm.org',
  },
];

console.log(noticeDetails[1].title);

// const container = document.getElementById('root');
const container = document.querySelector('.notice-list');
const noticeItemList = [];
let totalCount = noticeDetails.length;

const store = {
  currentPage: 1,
  feeds: [],
};

// init;
$(document).ready(function () {
  viewNoticeList();
});

function viewNoticeList() {
  for (let i = (store.currentPage - 1) * 10; i < store.currentPage * 10; i++) {
    let template = `  
    <li class="notice-item">
    <a onclick="location.href='{{__notice__}}'">${noticeDetails[i].title}</a>
    <span>${noticeDetails[i].domain.substr(0, 10).replace('/-/gi', '.')}</span>
    </li>
    `;

    template = template.replace(
      '{{__notice__}}',
      `/mypage/notice-detail.html?id=${noticeDetails[i].id}`
    );
    noticeItemList.push(template);

    container.innerHTML = noticeItemList.join('');
  }
}

$('button').click(function () {
  console.log(totalCount);
  // $('#boxWrap').append("<p class='original'>등장" + store.currentPage + '</p> ');
  // if (totalCount % pageSize > 0) {
  //   finalPageNo++;
  // }
  store.currentPage++;
  viewNoticeList();

  console.log(store.currentPage);
});
